#!/bin/sh

echo "runs 'cargo test' before push..."

cargo test

if [ $? -ne 0 ]; then
    echo "Error one or more tests failed"
    echo "Push cancelled try again"
    exit 1
fi

echo "All tests passed, continuing push"
exit 0